# -*- coding: utf-8 -*-
"""setup102203142.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15sRGxsIw5zfs7dFMhWwn-FalDQKRe3wn
"""

from setuptools import setup, find_packages

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(
    name="Topsis102203142",
    version="1.0.14",
    author="Aaradhya Sharma",
    author_email="sad314858@gmail.com",
    url="https://github.com/aradhyyySharrma8204/Topsis_DS_102203142",
    description="Topsis Assignment",
    long_description=long_description,
    long_description_content_type="text/markdown",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    install_requires=["pandas", "numpy"],
    entry_points={"console_scripts": ["Topsis102203142 = Topsis102203142.topsis:main"]},
)
